### ISSUE TITLE
/get_parking_rules Exception / 500 

### ISSUE THREAD

**Issue by mygzi** [ioxe/vouch-park#2]
**Sign text:**

["PAY TO", "PARK", "10am to 7pm", "ZONE", "3", "PERMIT", "REQUIRED", "EVERYDAY", "36 CFR 1004.12", "Except Federal Holidays"]

**Server error:**

ERROR in app: Exception on /get_parking_rules [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "ParkingController.py", line 18, in get_parking_Rules
    )
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/ykoren/Dev/GitHub/vouch-park/ParkingRuleEncoder.py", line 6, in default
    return o.__dict__
AttributeError: 'datetime.datetime' object has no attribute '__dict__'

**Comment by rashmi-iox** [comment]
Fixed the issue!
